### ISSUE TITLE
Error in Data Generation

### ISSUE THREAD

**Issue by mlcodeboy** [rootlu/MetaHIN#1]
Traceback (most recent call last):
  File "./MetaHIN/code/main.py", line 147, in <module>
    training(hml, model_save=True, model_file=model_filename,device=cuda_or_cpu)
  File "./MetaHIN/code/main.py", line 35, in training
    supp_xs_s, supp_ys_s, supp_mps_s, query_xs_s, query_ys_s, query_mps_s = zip(*train_data)  # supp_um_s:(list,list,...,2553)
ValueError: not enough values to unpack (expected 6, got 0)

**Comment by rootlu** [comment]
Hi, 

This error is caused by the error data format fed to the model, you need to process the original dataset to the right format with the code in /data/...

Due to GitHub's limitation on big files,  the current dataset is the original dataset.
I will update the processed data as soon as possible.

Thanks for you interest in our work!

**Comment by rootlu** [comment]
We have also uploaded the processed data of DBook and Movielens, please refer to the updated README.
Thanks. 
：）
